/*A LINGAUGEM SQL É DIVIDIDA EM SUBGRUPOS: DDL | DCL | DML | DTL | DQL*/

/* DDL = LINGUAGEM DE DIFINIÇÃO DOS DADOS(DATA DEFINITION LANGUAGE)

    DDL CREATE: COMANDO UTILIZADO PARA CRIAR ESTRUTURAS, POR EXEMPLO:
    CREATE DATABASE db_hcode;
    CREATE TABLE tb_news(
        id_news int,
        nome-usu varchar(250)
    );

    DDL ALTER: COMANDO PARA ALTERAR A ESTRUTURA DE UM OBJETO POR EXEMPLO DE TABELA:
    ALTER TABLE tb_news add column twitter varchar(30);

    DDL DROP: COMANDO UTILIZADO PARA ELIMMINAR ESTRUTURAS,POR EXEMPLO:
    DROP DATABASE db_hcode;
    DROP TABLE tb_news;

    DDL DELETE: COMANDO UTILIZADO PARA ELIMINAR DADOS,POR EXEMPLLO:
    DELETE FROM tb_carrinho WHERE cod_carrinho = 78236;

*/

/* DCL = LINGUAGEM DE CONTROLE DOS DADOS(DATA CONTROL LANGUAGE)

    DCL GRANT: O COMANDO GRANT É UM COMANDO DE CONTROLE DE DADOS, QUE SIGNIFICA CONCEDER ALGUM PRIVILÉGIO PARA UM USUÁRIO EM UM DETERMINADO OBJETO,EXEMPLO:
    CREATE USER 'ze'@'localhost'
    IDENTIFIED BY 'senhadoze'
    GRANT ALL ON db_hcode.* TO 'ze'@'localhost'
    |
    +->NESTE EXEMPLO XRIAMOS UM USUÁRIO CHAMADO ZE DENTRO DO SERVIDOR MYSQL QUE PODERÁ ACESSAR APENNAS QUANDO ESTIVER NA EMPRESA.ELE RECEBEY TODOS OS PRIVILÉGIOS NO BANCO DE DADOS CHAMADO db_hcode.

    DCL REVOKE: O COMANDO REVOKE COMO O NOME SUGERE, REVOGA UMA PERMISSÃO CONCEDIDA PREVIAMENTE POR MEIO DO COMANDO GRANT.
    REVOKE SELECT ON hcode.financeiro FROM jose
    |
    +->NO EXEMPLO ACIMA ESTAMOS REMOVENDO O PRIVILÉGIO DE REALIZER CONSULTAR DO USUÁRIO

*/

/* DML = LINGUAGEM DE MANIPULAÇÃO DOS DADOS(DATA MANIPULATION LANGUAGE)

    DML INSERT: COMANDO UTILIZADO PARA CADASTRAR INFORMALÇÕES DENTRO DE UMA TABELA NO BANCO DE DADOS.
    INSERT INTO tb_clientes(cod_cli, nome_cli, end_cli, sal_cli) VALUES (1,'José da Silva','AL.Santos,1000',5000.00)

    DML UPDATE: UM DOS COMANDOS MAIS IMPORTANTES PARA MANIPULAR AS INFORMAÇÕES, O COMANDO UPDATE PERMITE ALTERAR DADOS,POR EXEMPLO,MUDAR O VALOR DO SALÁRIO,ALTERAR UM ENDEREÇO E MUITO MAIS.
    UPDATE tb_pedidos SET valor_desconto = valor_total * 0.40 WHERE cod_cupom = 'BLACKFRIDAY' AND bln_fechado=0;

*/

/*DTL OU TCL = LINGUAGEM DE TRANSAÇÃO DE DADOS(TRANSACTION CONTROL LANGUAGE)

    DTL START TRANSACTION: UMA TRANSAÇÃO É UMA AÇÃO NO BANCO DE DADOS QUE PODE SER REALIZADA EM ETAPAS.SOMENTE QUANDO AS ETAPAS FOREM CONCLUÍDAS COM ÊXITO, SERÃO CONFIRMADAS COM O COMANDO START TRANSACTION INICIAMOS UMA TRANSAÇÃO CASO A TRANSAÇÃO SEJA CONFIRMADA TODAS AS AÇÕES QUE VIERAM APÓS A EXECUÇÃO DO COMANDO START TRANSACTION SERÃO EFETIVAMENTE EXECUTADOS.DO CONTRÁRIO TODA AÇÃO É DESFEITA ATÉ O COMANDO START TRANSACTION.

    DTL COMMIT: COMANDO UTILIZADO PARA CONFIRMAR UMA TRANSAÇÃO.
    COMMIT TRANSACTION;
    CASO TODAS AS ETAPAS DA TRANSAÇÃO FOI EXECUTADO COM SUCESSO ESTE COMANDO SERÁ EXECUTADDO, E ENCERRARÁ A TRANSAÇÃO CONFIRMANDO-A.É IMPRESCINDÍVEL QUE UM COMANDOO COMMIT ESTEJA ASSOCIADO A UM START TRANSACTION, UMA VEZ QUE SOMENTE CONFIRMAÁ TRANSAÇÕES QUE ESTÃO EM ABERTO

    DTL SAVEPOINT: SAVEPOINT nome_da_transação; COMANDO UTILIZADO PARA CRIAR UM PONTO DE RESTAURAÇÃO DENTRO DE UMA TRANSAÇÃO:
    SAVEPOINT nome_ponto;
    QUANDDO UMA TRANSAÇÃO É EXTENSA, PODEMOS CRIAR UM PONTO DE RESTAURAÇÃO E VOLTA NESTE PONTO SE NECESSÁRIO.NO PRÓXIMO COMANDO DE CONTROLE DE TRANSAÇÃO,VEREMOS QUE É POSSÍVEL CANCELAR UMA TRANSAÇÃO ATÉ UM PONTO DE RESTAURAÇÃO,ASSIM,TRANSAÇÕES MAIS LONGAS PODEM SER QUEBRADAS EM TRANSAÇÕES MENORES.

    DTL ROLLBACK: COMANDO UTILIZADO PARA CANCELAR TRANSAÇÕES, POR EXEMPLO:
    ROLLBACK TRANSACTION;
    TODAS AS ETAPAS DESDE O COMANDO START TRANSACTION SERÃO CANCELADAS, CASO UM SAVEPOINT TENHA SIDO CCRIADO, É POSSÍVEL VOLTAR ATÉ ESTE.É POSSÍVEL CANCELAR UM SAVEPOINT,ELIMINANDO UMA ETAPA QUE FOI SALVA ATÉ QUELE INSTANTE POR MEIO DO COMANDO SAVEPOINT NOME;
    ESTE COMANDO NECESSITA QUE UMA TRANSAÇÃO TENHA SIDO INICIADA, POR MEIO DO COMANDO START TRANSACTION.

*/

/*DQL = LINGUAGEM DE CONSULTA DE DADOS(DATA QUERY LANGUAGE)

    DQL SELECT: PRINCIPAL E ÚNICO COMANDO DO GRUPO DQL,O COMANDO SELECT,É SEM DÚVIDA O MAIS USADO EM BANCO DE DADOS.
    SELECT * FROM tb_cliente
    IRÁ EXIBIR TODOS OS DADOS DA TABELA CLIENTE ESSE É O COMANDO QUE MAIS POSSUI CLÁUSULAS E OPERADORES.
    TAMBÉM É UM COMANDO QUE PODE FICAR EXTENSO UTILIZANDO A CLÁUSULA JOIN PARA AGRUPAR VÁRIAS CONSULTAS AOS MESMO TEMPO.VEREMOS MAIS SOBRE O COMANDO SELECT.

*/