--ORDER BY : COMO A GENTE FAZ PARA ORDENAR/ORGANIZAR NOSSO SELECT, PODE SER EM ORDEM ALFABETICA, ORDEM NUMERICA, ASCENDENTE(ASC) E DESCENDENTE(DESC).ORDER BY SEMPRE ESTARA NO FINAL DO COMANDO.

SELECT * FROM tb_funcionarios ORDER BY nome;

SELECT * FROM tb_funcionarios ORDER BY 2;

SELECT * FROM tb_funcionarios ORDER BY salario DESC, nome;

SELECT * FROM tb_funcionarios ORDER BY salario LIMIT 0, 3;

SELECT * FROM tb_funcionarios WHERE YEAR(admissao) = 2016 AND MONTH(admissao) = 5 ORDER BY salario LIMIT 0, 3;



