CREATE DATABASE hcode;
USE hcode;

/*PARA CRIAR UMA TABELA(ENTIDADE)*/
CREATE TABLE clientes (/*DENTRO PONHA AS COLUNAS QUE VOCÊ DESEJA TER DENTRO DESSA TABELA*/
    id INT,
    nome VARCHAR(100)
);

/*INSERINDO VALORES DENTRO DA TABELA*/
INSERT INTO clientes VALUES (1,'José da silva');

/*INSERINDO VALORES DENTRO DA TABELA,ANTES PASSANDO A ORDEM DAS COLUNAS QUE IREMOS PASSAR OS VALORES*/
INSERT INTO clientes (nome, id) VALUES('João da silva', 2);

/*COMANDO DE CONSULTA; SELECIONAR *(TUDO) DENTRO DE clientes*/
SELECT * FROM clientes;