/*SUBQUERY : são consultas dentro de outras consultas.Imagina que voce pode executar o comando select e com base no resultado dessa consulta voce quer executar uma outra consulta,comando super interessante

ESTAMOS USANDO O MYSQL NESSE CASO:
*/

--PRIMEIRO O MYSQL VAI EXECUTAR O SELECT(ELE GUARDA O RESULTADO DESSE SELECT NA MEMORIA) E DEPOIS IRA EXECUTAR O QUE ESTA FORA DOS PARENTESES,SEMPRE DE DENTRO PARA FORA (1(2(3))) = IRA EXECUTAR O 3,DEPOIS O 2 E DEPOIS O 1
--IN ira conseguir pegar os dados da lista para ser usado na proxima consulta
DELETE FROM tb_pessoas WHERE idpessoa IN(SELECT idpessoa FROM tb_pessoas WHERE desnome LIKE 'J%');


--SE CONSEGUIR SEMPRE PREFIRA USAR O JOIN(QUE TEM O RELACIONAMENTE CHAVE PRIMARIA E CHAVE ESTRANGEIRA IRA ESTABELECER A LIGAÇÃO E FAZER A CONSULTA), MAS CASO NAO TENHA O RELACIONAMENTO CHAVE PRIMARIA E CHAVE ESTRANGEIRA USE A SUBQUERY
--SUBQUERYS SEMPRE ESCRITA ENTRE '()' PARENTESES E SEMPRE RETORNAM UMA COLUNA COMO INFORMACAO