/*DESTRUA O BANCO E TUDO DENTRO DELE*/
DROP DATABASE banco;

/*DESTRUA O BANCO E TUDO DENTRO DELE*/
DROP DATABASE hcode;

/*CRIE UM BANCO*/
CREATE DATABASE hcode;

/*CRIANDO TABELA E DEFININDO SUAS COLUNAS*/
CREATE TABLE tb_funcionarios (
    id INT,/*INTEIRO*/
    nome VARCHAR(100),/*CARACTERES VARIAVEIS ATE 100*/
    salario DECIMAL(10,2),/*DECIMAL ONDE TEM 10 NUMEROS E DESSES 10, 2 SAO DECIMAIS,EX: 12345678.12 */
    admissao DATE,/*ANO-MES-DIA*/
    sexo ENUM('F','M'),/*DEFINE VALORES PRE-DEFINIDOS*/
    cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP()/*SEGUNDOS Q VEM DESDE DE 01/01/1970, É UMA DATA GRAVADA EM NUMEROS INTEIROS. QUEREMOS CADASTRAR A DATA NO MEMONTO EM A PESSOA EXECUTAR O ENVIO DESSA TABELA, O SQL PEGANDO AUTOMATICAMENTE,USE DEFAULT(PADRÃO), CURRENT(ATUAL)_TIMESTAMP()*/
);

/*INSERINDO DADOS NO BANCO DE DADOS*/
INSERT INTO tb_funcionarios VALUES(1, 'Pedro Henrique', 4999.99, '2020-01-01', 'M', NULL);

/*EXIBINDO O BANCO DE DADOS*/
SELECT * FROM tb_funcionarios;

